INSERT INTO [dbo].[Role] (Code, Description)
VALUES 
	('ADM', 'Administration'),
	('A', 'Athlete'),
	('C', 'Coach');

INSERT INTO [dbo].[EventList] (Name)
VALUES
	('Men''s 50m Backstroke'),
	('Men''s 100m Backstroke'),
	('Men''s 200m Backstroke'),
	('Men''s 50m Breaststroke'),
	('Men''s 100m Breaststroke'),
	('Men''s 200m Breaststroke'),
	('Men''s 50m Butterfly'),
	('Men''s 100m Butterfly'),
	('Men''s 200m Butterfly'),
	('Men''s 50m Freestyle'),
	('Men''s 100m Freestyle'),
	('Men''s 200m Freestyle'),
	('Men''s 400m Freestyle'),
	('Men''s 800m Freestyle'),
	('Men''s 1500m Freestyle'),
	('Men''s 4x100m Freestyle Relay'),
	('Men''s 4x200m Freestyle Relay'),
	('Men''s 100m Individual Medly'),
	('Men''s 200m Individual Medly'),
	('Men''s 400m Individual Medly'),
	('Men''s 4x100m Medly Relay'),
	('Women''s 50m Backstroke'),
	('Women''s 100m Backstroke'),
	('Women''s 200m Backstroke'),
	('Women''s 50m Breaststroke'),
	('Women''s 100m Breaststroke'),
	('Women''s 200m Breaststroke'),
	('Women''s 50m Butterfly'),
	('Women''s 100m Butterfly'),
	('Women''s 200m Butterfly'),
	('Women''s 50m Freestyle'),
	('Women''s 100m Freestyle'),
	('Women''s 200m Freestyle'),
	('Women''s 400m Freestyle'),
	('Women''s 800m Freestyle'),
	('Women''s 1500m Freestyle'),
	('Women''s 4x100m Freestyle Relay'),
	('Women''s 4x200m Freestyle Relay'),
	('Women''s 100m Individual Medly'),
	('Women''s 200m Individual Medly'),
	('Women''s 400m Individual Medly'),
	('Women''s 4x100m Medly Relay');