INSERT INTO [dbo].[Sports] (SportName, Season)
VALUES
	('Cheer Team', 'Fall'),
	('Cross Country', 'Fall'),
	('Football', 'Fall'),
	('Dance Team', 'Fall/Winter'),
	('Soccer', 'Fall'),
	('Volleyball', 'Fall'),
	('Other', 'Fall'),
	('Swim', 'Winter'),
	('Basketball', 'Winter'),
	('Wrestling', 'Winter'),
	('Other', 'Winter'),
	('Baseball', 'Spring'),
	('Softball', 'Spring'),
	('Golf', 'Spring'),
	('Tennis', 'Spring'),
	('Track & Field', 'Spring'),
	('Other', 'Spring');

INSERT INTO [dbo].[MuscleList] (Name)
VALUES
	('Chest'),
	('Back'),
	('Triceps'),
	('Deltoids'),
	('Biceps'),
	('Abs'),
	('Quadriceps'),
	('Hamstrings'),
	('Calves'),
	('Forearms'),
	('Trapezius');

INSERT INTO [dbo].[Roles] (RoleName)
VALUES
	('Administration'),
	('Athlete'),
	('Coach');

INSERT INTO [dbo].[MovementList] (Name)
VALUES
	('Back Extension'),
	('Bear Crawl'),
	('Bench Press'),
	('Bicep Curl'),
	('Bicycling'),
	('Box Jump'),
	('Burpee'),
	('Butt Kicker'),
	('Calf Raise'),
	('Clean (Hang)'),
	('Clean (Power)'),
	('Clean (Squat)'),
	('Crunch'),
	('Dancing'),
	('Deadlift'),
	('Dip (Box)'),
	('Dip (Ring)'),
	('Flutter Kick'),
	('Good Morning'),
	('Handstand Push Up'),
	('Handstand'),
	('High Knee'),
	('Hiking'),
	('Jogging'),
	('Jump Rope'),
	('Jumping Jack'),
	('Knees to Elbows'),
	('Leg Press'),
	('Leg Raise'),
	('Lunge'),
	('Mountain Climber'),
	('Muscle Up'),
	('Plank (Side)'),
	('Plank'),
	('Pull Up'),
	('Push Jerk'),
	('Push Up'),
	('Rope Climb'),
	('Row'),
	('Running'),
	('Russian Twist'),
	('Shoulder Press'),
	('Shuttle Run'),
	('Sit Up'),
	('Skipping'),
	('Snatch (Hang)'),
	('Snatch (Power)'),
	('Snatch (Squat)'),
	('Sprint'),
	('Squat (Air)'),
	('Squat (Back)'),
	('Squat (Front)'),
	('Squat (Overhead)'),
	('Squat Jump'),
	('Stair Run'),
	('Step Up'),
	('Swimming'),
	('Walking'),
	('Wall Sit'),
	('Other (Please Specify)');